//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelDBEntities : DbContext
    {
        public hotelDBEntities()
            : base("name=hotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Fridge> Fridges { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Fridge> Product_Fridge { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Storage> Storages { get; set; }
        public virtual DbSet<Storage_Product> Storage_Product { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<view_StorageProductAmount> view_StorageProductAmount { get; set; }
        public virtual DbSet<view_FridgeProductAmount> view_FridgeProductAmount { get; set; }
        public virtual DbSet<view_RoomReservations> view_RoomReservations { get; set; }
        public virtual DbSet<view_AllPayedReservations> view_AllPayedReservations { get; set; }
    }
}
