//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Fridge
    {
        public int id_fr { get; set; }
        public int id_pr { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Fridge Fridge { get; set; }
        public virtual Product Product { get; set; }
    }
}
