//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_RoomReservations
    {
        public Nullable<int> beds { get; set; }
        public Nullable<decimal> price_per_day { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public int id_re { get; set; }
        public int id_ro { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<decimal> price_total { get; set; }
    }
}
